function createCookie(name,value,days){var expires;if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));expires="; expires="+date.toGMTString()}else{expires=""}
document.cookie=encodeURIComponent(name)+"="+encodeURIComponent(value)+expires+"; path=/"}
function readCookie(name){var nameEQ=encodeURIComponent(name)+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)===' ')
c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0)
return decodeURIComponent(c.substring(nameEQ.length,c.length))}
return null}
function eraseCookie(name){createCookie(name,"",-1)}
function checkForInputMyOverview(element){var e=$(element).val().toLowerCase();if($(element).val().length>0){$('.my-search-region').addClass('tab-search-my');var lookupCards=$('.lookup-cards').find('.lookup-card');lookupCards.hide().filter((function(index){return $(this).data('name').toLowerCase().indexOf(e)>=0})).show();$('.group-timing-btns').animate({opacity:0},100);$('.href-search').attr('href','/moodle/course/search.php?search='+e);$('.search-all-box').show()}else{$('.group-timing-btns').animate({opacity:1},100);$('.my-search-region').removeClass('tab-search-my');$('.lookup-cards .lookup-card').show();$('.search-all-box').hide()}}
$(document).ready(function(){$('.lectmode-btn').on("click",function(){if($('body').hasClass('lectmode')){$('body').removeClass('lectmode');eraseCookie('lectmode')}else{$('body').addClass('lectmode');createCookie('lectmode',1,1)}});if(readCookie('lectmode')==1){$('body').addClass('lectmode')}
$('input.my-overview-search').each(function(){checkForInputMyOverview(this)});$('input.involve-checkbox').each(function(){$(this).change(function(){$('.involve-desc').toggleClass('d-none',!($(this).is(":checked")));$('.involve-not').toggleClass('d-none',($(this).is(":checked")))})});$('a.involve-info-link').each(function(){$(this).attr('href',$(this).attr('href')+window.location.search)});$('input.my-overview-search').on('change keyup',function(){checkForInputMyOverview(this)});var mLangs=0;function addMlangButton(el){var elParent=$(el).wrap('<p/>').parent();var idNameHtml=elParent.html();var elEN=el+'EN';var elPL=el+'PL';if(typeof idNameHtml!=='undefined'){var idNameENhtml=idNameHtml.replace(/name="(.*?)"/g,'').replace(el.replace('#',''),elEN.replace('#','')).replace(/{mlang pl}(.*?){mlang}/g,'').replace(/{(.*?)}/g,'');var idNamePLhtml=idNameHtml.replace(/name="(.*?)"/g,'').replace(el.replace('#',''),elPL.replace('#','')).replace(/{mlang en}(.*?){mlang}/g,'').replace(/{(.*?)}/g,'');var customMlangButtonHtml='<a data-toggle="collapse" href="#mlang_buttons_rows_'+mLangs+'" class="btn btn-icon text-primary" aria-expanded="false" aria-controls="mlang_buttons_rows"><i class="icon fa fa-globe text-primary"></i></a>\n\
<div class="mlang_buttons_rows collapse" id="mlang_buttons_rows_'+mLangs+'"><div class="row mlang_buttons_row"><label for="nameEN"><img src="/moodle/theme/enauczanie/pix/custom/en.png" alt="en"></label>'+idNameENhtml+'</div>\n\
                <div class="row mlang_buttons_row"><label for="namePL"><img src="/moodle/theme/enauczanie/pix/custom/pl.png" alt="en"></label>'+idNamePLhtml+'</div></div>';elParent.html(idNameHtml+customMlangButtonHtml);mLangs++;$(el).unwrap();$(elEN).on('input',function(){$(el).val('{mlang en}'+$(elEN).val()+'{mlang}{mlang pl}'+$(elPL).val()+'{mlang}')});$(elPL).on('input',function(){$(el).val('{mlang en}'+$(elEN).val()+'{mlang}{mlang pl}'+$(elPL).val()+'{mlang}')})}}
addMlangButton('#id_name');addMlangButton('#id_title');addMlangButton('#id_fullname');addMlangButton('#id_name_value');addMlangButton('#id_s_theme_enauczanie_heroTitle');addMlangButton('#id_s_theme_enauczanie_heroDesc1');addMlangButton('#id_s_theme_enauczanie_heroDesc2');addMlangButton('#id_s_theme_enauczanie_footerDesc');$('.mlang_helper_input').each(function(i){let input=$(this).find('input');let txtarea=$(this).find('textarea');if(input){addMlangButton('#'+input.attr('id'))}
if(txtarea){addMlangButton('#'+txtarea.attr('id'))}});for(var i=0;i>=0;i++){var id='#id_answer_editor_'+i;if($(id).length){addMlangButton(id)}else{break}}
for(var i=0;i>=0;i++){var id='#id_response_editor_'+i;if($(id).length){addMlangButton(id)}else{break}}
for(var i=0;i>=0;i++){var id='#id_choices_'+i+"_answer";if($(id).length){addMlangButton(id)}else{break}}
for(var i=0;i>=0;i++){var id='#id_subanswers_'+i;if($(id).length){addMlangButton(id)}else{break}}
for(var i=0;i>=0;i++){var id='#id_answer_'+i;if($(id).length){addMlangButton(id)}else{break}}})